.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- 
 ERROR 2016-10-06 11:37:23,851 base 8584 139849447732992 Internal Server Error: /articles/add/ 
Traceback (most recent call last):
  File "/home/midas/Documentos/infa_web_folder/dev_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 123, in get_response
    response = middleware_method(request)
  File "/home/midas/Documentos/infa_web_folder/InfaWeb/infa_web/apps/base/middleware.py", line 10, in process_request
    manageParameters = ManageParameters(request.db)
AttributeError: 'WSGIRequest' object has no attribute 'db'
.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- 
 ERROR 2016-10-06 11:38:03,888 base 8622 139640124208896 Internal Server Error: /articles/add/ 
Traceback (most recent call last):
  File "/home/midas/Documentos/infa_web_folder/dev_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 123, in get_response
    response = middleware_method(request)
  File "/home/midas/Documentos/infa_web_folder/InfaWeb/infa_web/apps/base/middleware.py", line 45, in process_request
    manageParameters = ManageParameters(request.db)
AttributeError: 'WSGIRequest' object has no attribute 'db'
.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- 
 ERROR 2016-10-06 11:38:06,159 base 8622 139640124208896 Internal Server Error: /articles/add/ 
Traceback (most recent call last):
  File "/home/midas/Documentos/infa_web_folder/dev_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 123, in get_response
    response = middleware_method(request)
  File "/home/midas/Documentos/infa_web_folder/InfaWeb/infa_web/apps/base/middleware.py", line 45, in process_request
    manageParameters = ManageParameters(request.db)
AttributeError: 'WSGIRequest' object has no attribute 'db'
